version: '2'
services:
  web:
    build: build/docker/
    volumes:
      - /tmp
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring-boot-demo
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=boot-demo