version: '2'
services:
  web:
    build: ./build/docker/
    command: gradle clean build buildDocker
    volumes:
      - /tmp
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres